### ISSUE TITLE
WEB - 11. Send Images - getting following net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by LadikCZ** [firebase/friendlychat-web#144]
Followed step by step tutorial but i am getting following error when i trie to send and image. Really cant find out where is the problem. I even tried to start over or use the complete web solution provided from you in directory web. Still the same error.

https://firebasestorage.googleapis.com/v0/b/friendlychat-50777.appspot.com/o?name=3zaMioik1ghV9AvP3Ft7TEHiCvX2%2F1484315618812%2FDSC_0698.JPG net::ERR_CONNECTION_CLOSEDEa @ firebase.js:561b @ firebase.js:562(anonymous function) @ firebase.js:555

Can someone help me please?

This is my app 
https://friendlychat-50777.firebaseapp.com

**Comment by rzhang86** [comment]
I have a similar but not identical error when sending an image message:
Failed to load resource: net::ERR_UNKNOWN_URL_SCHEME
In the chat box, the presence of a new image message is reflected however an image-missing placeholder icon is shown instead of the image itself. I can confirm the image is in the Cloud Storage backend. Something is wrong with the pathing or authentication in the tutorial.

**Comment by nicolasgarnier** [comment]
I've re-worked the way images are displayed and URL generated. Hopefully this should not happen anymore. Please post again if it does.
