### ISSUE TITLE
Unable to get messaging token

### ISSUE THREAD

**Issue by SuperRoo123** [firebase/friendlychat-web#281]
Hi
have followed the project and got my function up there..adds fine to the database...but... says "Unable to get messaging token. " I believe it is to do with the firebase-messaging-sw.js not being initialised.

Am hosting on firebase and followed the project...what's the solution.

**Comment by nicolasgarnier** [comment]
Hey @SuperRoo123 sorry for the delay. It could happen if you have blocked the notifications when you were prompted to enable them.

Yu can follow this to re-enable them: https://support.google.com/chrome/answer/3220216?co=GENIE.Platform%3DDesktop&hl=en

Otherwise could you check the error message? It may contain more details :)
